### ISSUE TITLE
Your discord invite link is broken, wanted to ask about how to set up Vault

### ISSUE THREAD

**Issue by ManicQuinn** [nanoflux/networks#39]
I have Vault and an Eco Plugin, the plugin page on Modrinth mentioned I can sell Networks with Vault Economies, can't seem to see that in the conf file

**Comment by nanoflux** [comment]
Hey, thanks for reporting! The link on Modrinth is fixed now and I updated the description.
The economy feature was abandoned in v1.2.1 after it wasn't used by anyone for almost a year.
If enough people want it, I will reimplement it in v3
